<?php
/**
 * @file
 * This is my module.
 */
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\Request; 
 /**
 * Implements hook_form_alter().
 */
function custom_site_information_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
	    # get config formAPI variable value
	    $config = \Drupal::config('custom_site_information.settings');
		$configVar = $config->get('formapi');
		
		$form['site_information']['formapi'] = array(
		'#title' => t('Site API Key'),
		'#description' => t('Site API Key'),
		'#type' => 'textfield',
		'#default_value' =>isset($configVar)?$configVar:'',
		);
		$form['actions']['submit']['#value'] = 'Update Configuration';
		$form['#submit'][] = 'custom_site_information_handler';
  }
}
/*
 Custom Submit Handler Callback Function
*/
function custom_site_information_handler($form, &$form_state) {
	//echo "<pre>";
	//print_r($form_state->getValues());
	//die;
	$config = \Drupal::service('config.factory')->getEditable('custom_site_information.settings');
    $config->set('formapi', $form_state->getValues()['formapi'])
    ->save();
	drupal_set_message('Site API Key has been saved with the Value:'  . $form_state->getValues()['formapi']);
	
}
